### ISSUE TITLE
Availibility of the dataset

### ISSUE THREAD

**Issue by didulle** [PKU-IMRE/VERI-Wild#1]
Hi
I have read your CVPR paper and I am interested on testing my own model on this dataset. Do you have an idea when the dataset will be available? 
Thanks

**Comment by ratnesh1729** [comment]
Would be of great info to have ? Whether the authors @PKU-IMRE  are planning a competition in a CV conferences ?

**Comment by YihangLou** [comment]
Thank you for your attention. Now, the dataset has been released.
