### ISSUE TITLE
About the annotation format

### ISSUE THREAD

**Issue by DTennant** [PKU-IMRE/VERI-Wild#2]
what is the annotation format of those txt files in the train test split folder？
thanks

**Comment by DTennant** [comment]
Also, I noticed that there is not camera id label in the dataset?

**Comment by YihangLou** [comment]
The list is a/b....... 'a' means the folder, 'b.jpg' is the image name. Every image in the same folder is the same vehicle id.  We will add README in the split folder.

We are preparing more additional information such as capture time, camera ID etc. We will update the link on github within one or two weeks.

**Comment by PKU-IMRE** [comment]
Thank you for your attention. The additional information, e.g. capture time, camera ID etc, has been updated.
