### ISSUE TITLE
A simple baseline code that achieve high performance on this dataset

### ISSUE THREAD

**Issue by DTennant** [PKU-IMRE/VERI-Wild#4]
https://github.com/DTennant/reid_baseline_with_syncbn
This baseline achieves mAP 74.27%(77.42% after reranking) on the small test set

**Comment by PKU-IMRE** [comment]
This is a very surprising performance. Now, the best performance we can get is 66% mAP for resnet50 backbone and 37% mAP for VGGM on small test set. Our dataset does not remove the same camera ID images as the query in the gallery set, as in VERI-776, and not limit the number of images in the gallery dataset with the same ID as the query.  Hope you can get better performance.  We also released another dataset containing 10 million interference images. You can further validate your method on the dataset that joins the interference images. That will be even more challenging.

**Comment by ratnesh1729** [comment]
On small set I am also able to get good results of 70% mAP.. while on large - 51% .. 
https://arxiv.org/pdf/1901.01015.pdf

**Comment by DTennant** [comment]
> On small set I am also able to get good results of 70% mAP.. while on large - 51% ..
> [https://arxiv.org/pdf/1901.01015.pdf](http://xxx.itp.ac.cn/pdf/1901.01015.pdf)

Hi, Is your code open sourced ?

**Comment by ratnesh1729** [comment]
Hello
You can get 3 out of 4 sampling techniques from this branch 
https://github.com/VisualComputingInstitute/triplet-reid/blob/sampling/loss.py

Best,
