### ISSUE TITLE
dataset uploaded has only 39385 vehicle. 

### ISSUE THREAD

**Issue by saghiralfasly** [PKU-IMRE/VERI-Wild#5]
The uploaded dataset in google drive and baidu has only 39385 folders which mean only 39385 vehicles. Is there 1286 vehicle folders missing?

**Comment by SikaStar** [comment]
> The uploaded dataset in google drive and baidu has only 39385 folders which mean only 39385 vehicles. Is there 1286 vehicle folders missing?

Hi,
Please check the file you have downloaded, the dataset I have downloaded has 40671 folders

**Comment by saghiralfasly** [comment]
> Hi,
> Please check the file you have downloaded, the dataset I have downloaded has 40671 folders

Sorry, the issue was from my side. last file 23 was not downloaded completely. Thank you.
