### ISSUE TITLE
understanding the mAP code

### ISSUE THREAD

**Issue by ratnesh1729** [PKU-IMRE/VERI-Wild#6]
Thanks for uploading the evaluation code. Also thank you again for the dataset.

Wanted to understand this line https://github.com/PKU-IMRE/VERI-Wild/blob/master/test-code/mAP.py#L27
-- what is the purpose of this function argument/variable "repeat" ? This was fixed to 1 for all the results in your paper ?
-- Also you do not perform any filtering on the test and query sets inside "train_test_splits/"  ? 

Thanks!

**Comment by PKU-IMRE** [comment]
Yes, in our dataset, the repeat is  1. I will delete the "repeat" parameter.

**Comment by PKU-IMRE** [comment]
Thank you for your comments. In our dataset, we fix the query set and reference set, which is different between VehicleID dataset. I set the repeat parameter in VehicleID dataset and  forget to delete it.
