### ISSUE TITLE
explanation about evaluation metrics 

### ISSUE THREAD

**Issue by fangliang425** [PKU-IMRE/VERI-Wild#7]
Hi,
It seems like there is no argument of "camera id" in your [evaluation code](https://github.com/PKU-IMRE/VERI-Wild/blob/master/test-code/mAP.py#L27). However, [evaluation code](https://github.com/Cysu/open-reid/blob/master/reid/evaluation_metrics/ranking.py#L18) in Person Re-identification considers the "camera id", could you please explain if there is any difference between these two?

**Comment by PKU-IMRE** [comment]
Thank you for your comment. It's my mistake. Since the student who responsible for the experiments has graduated, I write the test code. Confirming with the student, you are right. I will modify the test code. The experiments in the paper have considered the camera ids. Your can compare fairly.
